server:
  port: 8080
spring:
  datasource:
    username: root
    password: lijinshan
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cart?useUnicode=true&characterEncoding=utf-8


mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mapper/*Mapper.xml

